// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/arbeitszeiten/:arbeitszeit": {
    params: {
      "arbeitszeit": string;
    };
  };
  "/projekte": {
    params: {};
  };
  "/kunden": {
    params: {};
  };
  "/projekte/neu": {
    params: {};
  };
  "/ueberstunden": {
    params: {};
  };
  "/mitarbeiter": {
    params: {};
  };
  "/mitarbeiter/:mitarbeiter": {
    params: {
      "mitarbeiter": string;
    };
  };
  "/mitarbeiter/neu": {
    params: {};
  };
  "/mitarbeiter/new": {
    params: {};
  };
  "/fehlzeiten": {
    params: {};
  };
  "/fehlzeiten/:fehlzeiten": {
    params: {
      "fehlzeiten": string;
    };
  };
  "/fehlzeiten/neu": {
    params: {};
  };
  "/fehlzeiten/new": {
    params: {};
  };
  "/kunden/neu": {
    params: {};
  };
  "/meinProfil": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/NavItem": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/urlaub": {
    params: {};
  };
  "/urlaub/:urlaub": {
    params: {
      "urlaub": string;
    };
  };
  "/urlaub/neu": {
    params: {};
  };
  "/urlaub/new": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/neu": {
    params: {};
  };
  "/me": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/arbeitszeiten/:arbeitszeit" | "/projekte" | "/kunden" | "/projekte/neu" | "/ueberstunden" | "/mitarbeiter" | "/mitarbeiter/:mitarbeiter" | "/mitarbeiter/neu" | "/mitarbeiter/new" | "/fehlzeiten" | "/fehlzeiten/:fehlzeiten" | "/fehlzeiten/neu" | "/fehlzeiten/new" | "/kunden/neu" | "/meinProfil" | "/settings" | "/NavItem" | "/logout" | "/search" | "/urlaub" | "/urlaub/:urlaub" | "/urlaub/neu" | "/urlaub/new" | "/about" | "/login" | "/neu" | "/me";
  };
  "routes/arbeitszeiten.$arbeitszeit.tsx": {
    id: "routes/arbeitszeiten.$arbeitszeit";
    page: "/arbeitszeiten/:arbeitszeit";
  };
  "routes/projekte._index.tsx": {
    id: "routes/projekte._index";
    page: "/projekte";
  };
  "routes/kunden._index.tsx": {
    id: "routes/kunden._index";
    page: "/kunden";
  };
  "routes/projekte.neu.tsx": {
    id: "routes/projekte.neu";
    page: "/projekte/neu";
  };
  "routes/ueberstunden.tsx": {
    id: "routes/ueberstunden";
    page: "/ueberstunden";
  };
  "routes/mitarbeiter.tsx": {
    id: "routes/mitarbeiter";
    page: "/mitarbeiter" | "/mitarbeiter/:mitarbeiter" | "/mitarbeiter/neu" | "/mitarbeiter/new";
  };
  "routes/mitarbeiter.$mitarbeiter.tsx": {
    id: "routes/mitarbeiter.$mitarbeiter";
    page: "/mitarbeiter/:mitarbeiter";
  };
  "routes/mitarbeiter._index.tsx": {
    id: "routes/mitarbeiter._index";
    page: "/mitarbeiter";
  };
  "routes/mitarbeiter.neu.tsx": {
    id: "routes/mitarbeiter.neu";
    page: "/mitarbeiter/neu";
  };
  "routes/mitarbeiter.new.tsx": {
    id: "routes/mitarbeiter.new";
    page: "/mitarbeiter/new";
  };
  "routes/fehlzeiten.tsx": {
    id: "routes/fehlzeiten";
    page: "/fehlzeiten" | "/fehlzeiten/:fehlzeiten" | "/fehlzeiten/neu" | "/fehlzeiten/new";
  };
  "routes/fehlzeiten.$fehlzeiten.tsx": {
    id: "routes/fehlzeiten.$fehlzeiten";
    page: "/fehlzeiten/:fehlzeiten";
  };
  "routes/fehlzeiten._index.tsx": {
    id: "routes/fehlzeiten._index";
    page: "/fehlzeiten";
  };
  "routes/fehlzeiten.neu.tsx": {
    id: "routes/fehlzeiten.neu";
    page: "/fehlzeiten/neu";
  };
  "routes/fehlzeiten.new.tsx": {
    id: "routes/fehlzeiten.new";
    page: "/fehlzeiten/new";
  };
  "routes/kunden.neu.tsx": {
    id: "routes/kunden.neu";
    page: "/kunden/neu";
  };
  "routes/meinProfil.tsx": {
    id: "routes/meinProfil";
    page: "/meinProfil";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/NavItem.tsx": {
    id: "routes/NavItem";
    page: "/NavItem";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/search.tsx": {
    id: "routes/search";
    page: "/search";
  };
  "routes/urlaub.tsx": {
    id: "routes/urlaub";
    page: "/urlaub" | "/urlaub/:urlaub" | "/urlaub/neu" | "/urlaub/new";
  };
  "routes/urlaub.$urlaub.tsx": {
    id: "routes/urlaub.$urlaub";
    page: "/urlaub/:urlaub";
  };
  "routes/urlaub._index.tsx": {
    id: "routes/urlaub._index";
    page: "/urlaub";
  };
  "routes/urlaub.neu.tsx": {
    id: "routes/urlaub.neu";
    page: "/urlaub/neu";
  };
  "routes/urlaub.new.tsx": {
    id: "routes/urlaub.new";
    page: "/urlaub/new";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/neu.tsx": {
    id: "routes/neu";
    page: "/neu";
  };
  "routes/me.tsx": {
    id: "routes/me";
    page: "/me";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/arbeitszeiten.$arbeitszeit": typeof import("./src/routes/arbeitszeiten.$arbeitszeit.tsx");
  "routes/projekte._index": typeof import("./src/routes/projekte._index.tsx");
  "routes/kunden._index": typeof import("./src/routes/kunden._index.tsx");
  "routes/projekte.neu": typeof import("./src/routes/projekte.neu.tsx");
  "routes/ueberstunden": typeof import("./src/routes/ueberstunden.tsx");
  "routes/mitarbeiter": typeof import("./src/routes/mitarbeiter.tsx");
  "routes/mitarbeiter.$mitarbeiter": typeof import("./src/routes/mitarbeiter.$mitarbeiter.tsx");
  "routes/mitarbeiter._index": typeof import("./src/routes/mitarbeiter._index.tsx");
  "routes/mitarbeiter.neu": typeof import("./src/routes/mitarbeiter.neu.tsx");
  "routes/mitarbeiter.new": typeof import("./src/routes/mitarbeiter.new.tsx");
  "routes/fehlzeiten": typeof import("./src/routes/fehlzeiten.tsx");
  "routes/fehlzeiten.$fehlzeiten": typeof import("./src/routes/fehlzeiten.$fehlzeiten.tsx");
  "routes/fehlzeiten._index": typeof import("./src/routes/fehlzeiten._index.tsx");
  "routes/fehlzeiten.neu": typeof import("./src/routes/fehlzeiten.neu.tsx");
  "routes/fehlzeiten.new": typeof import("./src/routes/fehlzeiten.new.tsx");
  "routes/kunden.neu": typeof import("./src/routes/kunden.neu.tsx");
  "routes/meinProfil": typeof import("./src/routes/meinProfil.tsx");
  "routes/settings": typeof import("./src/routes/settings.tsx");
  "routes/NavItem": typeof import("./src/routes/NavItem.tsx");
  "routes/_index": typeof import("./src/routes/_index.tsx");
  "routes/logout": typeof import("./src/routes/logout.tsx");
  "routes/search": typeof import("./src/routes/search.tsx");
  "routes/urlaub": typeof import("./src/routes/urlaub.tsx");
  "routes/urlaub.$urlaub": typeof import("./src/routes/urlaub.$urlaub.tsx");
  "routes/urlaub._index": typeof import("./src/routes/urlaub._index.tsx");
  "routes/urlaub.neu": typeof import("./src/routes/urlaub.neu.tsx");
  "routes/urlaub.new": typeof import("./src/routes/urlaub.new.tsx");
  "routes/about": typeof import("./src/routes/about.tsx");
  "routes/login": typeof import("./src/routes/login.tsx");
  "routes/neu": typeof import("./src/routes/neu.tsx");
  "routes/me": typeof import("./src/routes/me.tsx");
};