<meta name="viewport" content="width=device-width, initial-scale=1.0">
<div class="login-box">
  <h1 class="login-begruesung">Loggen Sie sich ein für Ihre Daten.</h1>

  <form method="post">
    <input class="login-input" type="text" name="username" placeholder="Username" required>
    <input class="login-input" type="password" name="password" placeholder="Password" required>
    <button class="login-button" type="submit">Einloggen</button>
    
    <div class="login-link-wrapper">
      <a href="/Passwort/Vergessen" class="login-link">Passwort vergessen?</a>
    </div>
  </form>
</div>
