<meta name="viewport" content="width=device-width, initial-scale=1.0">
<div class="usereingabe">
  <h1>Ändern Sie hier Ihr Passwort</h1>

  <form method="post" action="/Passwort/Zuruecksetzen?token=<?= $_GET['token']?>">
    
    <label for="password">Neues Passwort eingeben</label>
    <input class="eingabe-feld" type="password" id="password" name="password" placeholder="Neues Passwort" required>

    <label for="password_bestaetigen">Passwort erneut eingeben und bestätigen</label>
    <input class="eingabe-feld" type="password" id="password_bestaetigen" name="password_bestaetigen" placeholder="Passwort bestätigen" required>

    <button class="eingabe-feld" type="submit">Bestätigen</button>
  </form>

  <a href="/" class="button-link">Zurück zum Login</a>
</div>
